title: UCSF CALM Microscopy Wiki
logo: /assets/img/CALM-UCSF.png
description: Wiki
favicon: true
color-scheme: dark

# GitHub Pages settings
baseurl: "/wiki"
url: "https://UCSF-CALM.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/UCSF-CALM

navigation:
  - name: Home
    link: ./index.html
  - name: Microscopes
    link: ./pages/microscopes/Microscopes.html
    sublist:
      - name: Spinning Disk Confocal
        link: ./pages/microscopes/Spinning-Disk-Confocal.html
      - name: TIRF/N-STORM
        link: ./pages/microscopes/TIRF-STORM.html
      - name: Time Lapse
        link: ./pages/microscopes/Time-Lapse.html
      - name: 6D
        link: ./pages/microscopes/6D.html
      - name: Crest LFOV/C2
        link: ./pages/microscopes/Crest-C2.html
      - name: CSU-W1
        link: ./pages/microscopes/CSU-W1.html
      - name: AZ100 Light Sheet
        link: ./pages/microscopes/AZ100-Light-Sheet.html
      - name: OMX-SR
        link: ./pages/microscopes/OMX-SR.html
      - name: TruLive3D Light Sheet
        link: ./pages/microscopes/TruLive3D-Light-Sheet.html
      - name: C-Trap Optical Tweezers
        link: ./pages/microscopes/C-Trap-Optical-Tweezers.html
      - name: CVRI Microscopes
        link: ./pages/microscopes/CVRI-Nikon-Spinning-Disk-Confocal.html
   
  - name: Data Analysis
    link: ./pages/data-analysis/Data-Analysis.html
    sublist:
      - name: Workstations
        link: ./pages/data-analysis/Data-Analysis-Workstations.html
      - name: Storage & Compute
        link: ./pages/data-analysis/Data-Storage-and-Compute.html
      - name: Fiji/ImageJ
        link: ./pages/data-analysis/ImageJ-and-Variants.html
      - name: Huygens
        link: ./pages/data-analysis/Huygens.html
      - name: MATLAB
        link: ./pages/data-analysis/MATLAB.html
  - name: Sample Preparation
    link: ./pages/sample-preparation/Sample-Preparation.html
    sublist:
      - name: Dyes & Proteins
        link: ./pages/sample-preparation/Fluorescent-Proteins-for-Localization-Microscopy.html
      - name: Protocols
        link: ./pages/sample-preparation/Clearing-methods.html
      - name: Materials
        link: ./pages/sample-preparation/High-Precision-Coverslips.html
  - name: References & Education
    link: ./pages/references-and-education/Microscopy-References-and-Education.html
    sublist:
      - name: Courses
        link: ./pages/references-and-education/Microscopy-Courses.html
      - name: Books & Websites
        link: ./pages/references-and-education/Books-Websites-etc.html
      - name: Methods Examples
        link: ./pages/references-and-education/Examples-of-Microscope-Methods.html
  - name: CALM Information
    link: ./pages/calm-information/Other-CALM-Information.html
    sublist:
      - name: Quick Start Guides
        link: ./pages/calm-information/User-Quick-Start-Guides.html
      - name: iLab
        link: ./pages/calm-information/iLab.html
      - name: Acknowledgements
        link: ./pages/calm-information/Acknowledgements.html
  - name: Miscellaneous
    link: ./pages/miscellaneous/Miscellaneous.html
