title: Center For Advanced Light Microscopy Wiki (CALM) @ UCSF
logo: /assets/img/logo.jpg
description: Wiki
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: 
  - name: 
    icon: 
    link: 
navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
