title: UCSF CALM Microscopy Wiki
logo: /assets/img/CALM-UCSF.png
description: Wiki
favicon: true
color-scheme: dark

# GitHub Pages settings
baseurl: "/wiki"
url: "https://UCSF-CALM.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/UCSF-CALM 
navigation:
  - name: Home
    link: ./index.html
  - name: Microscopes
    link: ./pages/microscopes/Microscopes_517178884.html
    sublist:
      - name: Spinning Disk Confocal
        link: ./pages/microscopes/Spinning-Disk-Confocal_517178889.html
      - name: TIRF/N-STORM
        link: ./pages/microscopes/517178903.html
      - name: Time Lapse
        link: ./pages/microscopes/Time-Lapse_517182042.html
      - name: 6D
        link: ./pages/microscopes/6D_517182048.html
      - name: Crest LFOV/C2
        link: ./pages/microscopes/522589638.html
      - name: CSU-W1
        link: ./pages/microscopes/517182054.html
      - name: AZ100 Light Sheet
        link: ./pages/microscopes/AZ100-Light-Sheet_517182060.html
      - name: OMX-SR
        link: ./pages/microscopes/OMX-SR_517182062.html
      - name: TruLive3D Light Sheet
        link: ./pages/microscopes/TruLive3D-Light-Sheet_674609376.html
      - name: C-Trap Optical Tweezers
        link: ./pages/microscopes/C-Trap-Optical-Tweezers_698319820.html
      - name: CVRI Microscopes
        link: ./pages/microscopes/CVRI-Nikon-Spinning-Disk-Confocal_517182067.html
      - name: Weill Microscopes
        link: ./pages/microscopes/Weill--CSU-W1-SoRA-Spinning-Disk-Confocal_561953513.html
  - name: Data Analysis
    link: ./pages/data-analysis/Data-Analysis_517182106.html
    sublist:
      - name: Workstations
        link: ./pages/data-analysis/Data-Analysis-Workstations_517178905.html
      - name: Storage & Compute
        link: ./pages/data-analysis/Data-Storage-and-Compute_685901383.html
      - name: Fiji/ImageJ
        link: ./pages/data-analysis/ImageJ-and-Variants_517184301.html
      - name: Huygens
        link: ./pages/data-analysis/Huygens_517184442.html
      - name: MATLAB
        link: ./pages/data-analysis/MATLAB_517184427.html
  - name: Sample Preparation
    link: ./pages/sample-preparation/Sample-Preparation_517182102.html
    sublist:
      - name: Dyes & Proteins
        link: ./pages/sample-preparation/Fluorescent-Proteins-for-Localization-Microscopy_517197198.html
      - name: Protocols
        link: ./pages/sample-preparation/Clearing-methods_517184494.html
      - name: Materials
        link: ./pages/sample-preparation/High-Precision-Coverslips_517184498.html
  - name: References & Education
    link: ./pages/references-and-education/Microscopy-References-and-Education_517178908.html
    sublist:
      - name: Courses
        link: ./pages/references-and-education/Microscopy-Courses_517182136.html
      - name: Books & Websites
        link: ./pages/references-and-education/517182143.html
      - name: Methods Examples
        link: ./pages/references-and-education/Examples-of-Microscope-Methods_641107539.html
  - name: CALM Information
    link: ./pages/calm-information/Other-CALM-Information_517182095.html
    sublist:
      - name: Quick Start Guides
        link: ./pages/calm-information/User-Quick-Start-Guides_517182146.html
      - name: iLab
        link: ./pages/calm-information/iLab_701465591.html
      - name: Acknowledgements
        link: ./pages/calm-information/Acknowledgements_599783507.html
  - name: Miscellaneous
    link: ./pages/miscellaneous/Miscellaneous_517182118.html
